### ISSUE TITLE
[macOS] 报错 error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by xinyangt9** [zhxie/pcap2socks#10]
Release中下载的预编译版本与我自己用源码编译出的版本运行后都报错 error: No such file or directory (os error 2)，请问如何解决呢
<img width="568" alt="Screen Shot 2021-01-11 at 01 08 46" src="https://user-images.githubusercontent.com/55012776/104130033-8fad2680-53a9-11eb-9760-2f7ee8401840.png">
同时问一下，如果我没有理解错的话，-s与-p参数是设置为局域网内不存在的IP对吧。Switch端上的DNS该如何设置呢？

**Comment by zhxie** [comment]
From the screenshots, you may be using macOS. This may be caused by you not running under root privileges, and you can run it via `sudo`. Reference to [Troubleshoot](https://github.com/zhxie/pcap2socks#troubleshoot).

DNS is also proxied through SOCKS, so you can use any DNS you want on the Switch, like `8.8.8.8`.

---

从截图中看，你应该在使用 macOS。这可能是由于你没有在 root 权限下运行导致的，并且你可以通过 `sudo` 运行。参考 [Troubleshoot](https://github.com/zhxie/pcap2socks#troubleshoot)。

DNS 同样将经过 SOCKS 代理，因此你可以在 Switch 上使用任何你想使用的 DNS，比如`8.8.8.8`。

**Comment by xinyangt9** [comment]
Thanks!

**Comment by pigKinger** [comment]
学到了
