### ISSUE TITLE
连接一会就提示memory allocation of 671088640然后程序退出

### ISSUE THREAD

**Issue by MCLV** [zhxie/pcap2socks#9]
有救吗(´；ω；`)

**Comment by zhxie** [comment]
Thanks for your feedback. This issue was put forward in #7, and was solved in commit 47f8e1c6. Since I have not release a new one, you can build this repository or use [the build in this comment](https://github.com/zhxie/pcap2socks/issues/7#issuecomment-718812843).

Revision: Please use [the build in this comment](https://github.com/zhxie/pcap2socks/issues/8#issuecomment-719584264).

---

感谢反馈。这个问题已在 #7 中被描述并在 commit 47f8e1c6 得到解决。由于我暂未发布新的版本，你可以选择编译本项目或是使用[此回复中的 build](https://github.com/zhxie/pcap2socks/issues/7#issuecomment-718812843)。

修订：请使用[此回复中的 build](https://github.com/zhxie/pcap2socks/issues/8#issuecomment-719584264)。
